package project.pipepipe.shared.job

enum class SupportedJobType {
    FETCH_INFO,
    FETCH_FIRST_PAGE,
    FETCH_GIVEN_PAGE,
    GET_SUGGESTION,
    REFRESH_COOKIE,
    GET_SUPPORTED_SERVICES,
    SUBMIT_SPONSORBLOCK_SEGMENT,
    VOTE_SPONSORBLOCK_SEGMENT,
    FETCH_SPONSORBLOCK_SEGMENT_LIST
}